' <auto-generated/>
' This source file is part of the JSON serialization code and is not intended to be modified by you.
' Re-run the source generator will overwrite your changes in this file.
' Generated by: Nukepayload2.IO.Json.Serialization.NewtonsoftJson
Option Strict On
Option Infer On
Option Explicit On
Option Compare Binary
Imports Nukepayload2.AI.Providers.Deepseek.Models
Imports Newtonsoft.Json.Linq

Namespace Serialization
    Partial Class FimRequestWriter

        ''' <summary>
        ''' Writes <see cref="FimRequest"/> to JsonWriter.
        ''' </summary>
        Public Shared Sub WriteFimRequest(writer As Global.Newtonsoft.Json.JsonWriter, value As FimRequest)
            If value Is Nothing Then
                writer.WriteNull()
                Return
            End If

            writer.WriteStartObject()
            If value.Model IsNot Nothing Then
                writer.WritePropertyName("model")
                writer.WriteValue(value.Model)
            End If
            If value.Prompt IsNot Nothing Then
                writer.WritePropertyName("prompt")
                writer.WriteValue(value.Prompt)
            End If
            If value.Echo IsNot Nothing Then
                writer.WritePropertyName("echo")
                writer.WriteValue(value.Echo)
            End If
            If value.FrequencyPenalty IsNot Nothing Then
                writer.WritePropertyName("frequency_penalty")
                writer.WriteValue(value.FrequencyPenalty)
            End If
            If value.Logprobs IsNot Nothing Then
                writer.WritePropertyName("logprobs")
                writer.WriteValue(value.Logprobs)
            End If
            If value.MaxTokens IsNot Nothing Then
                writer.WritePropertyName("max_tokens")
                writer.WriteValue(value.MaxTokens)
            End If
            If value.PresencePenalty IsNot Nothing Then
                writer.WritePropertyName("presence_penalty")
                writer.WriteValue(value.PresencePenalty)
            End If
            If value.StopWords IsNot Nothing Then
                writer.WritePropertyName("stop")
                WriteFimStopWords(writer, value.StopWords)
            End If
            If value.Stream IsNot Nothing Then
                writer.WritePropertyName("stream")
                writer.WriteValue(value.Stream)
            End If
            If value.StreamOptions IsNot Nothing Then
                writer.WritePropertyName("stream_options")
                WriteStreamOptions(writer, value.StreamOptions)
            End If
            If value.Suffix IsNot Nothing Then
                writer.WritePropertyName("suffix")
                writer.WriteValue(value.Suffix)
            End If
            If value.Temperature IsNot Nothing Then
                writer.WritePropertyName("temperature")
                writer.WriteValue(value.Temperature)
            End If
            If value.TopP IsNot Nothing Then
                writer.WritePropertyName("top_p")
                writer.WriteValue(value.TopP)
            End If

            writer.WriteEndObject()
        End Sub ' WriteFimRequest

        ''' <summary>
        ''' Writes <see cref="StreamOptions"/> to JsonWriter.
        ''' </summary>
        Private Shared Sub WriteStreamOptions(writer As Global.Newtonsoft.Json.JsonWriter, value As StreamOptions)
            If value Is Nothing Then
                writer.WriteNull()
                Return
            End If

            writer.WriteStartObject()
            If value.IncludeUsage IsNot Nothing Then
                writer.WritePropertyName("include_usage")
                writer.WriteValue(value.IncludeUsage)
            End If

            writer.WriteEndObject()
        End Sub ' WriteStreamOptions

        ''' <summary>
        ''' Writes array of <see cref="String"/> to JsonWriter.
        ''' </summary>
        Private Shared Sub WriteIReadOnlyListOfString(writer As Global.Newtonsoft.Json.JsonWriter, value As IReadOnlyList(Of String))
            If value Is Nothing Then
                writer.WriteNull()
                Return
            End If

            writer.WriteStartArray()
            For Each item In value
                writer.WriteValue(item)
            Next
            writer.WriteEndArray()
        End Sub

        ''' <summary>
        ''' Writes composite type <see cref="FimStopWords"/> with type-based discriminator to JsonWriter.
        ''' </summary>
        Private Shared Sub WriteFimStopWords(writer As Global.Newtonsoft.Json.JsonWriter, value As FimStopWords)
            If value Is Nothing Then
                writer.WriteNull()
                Return
            End If
            If value.StringValue IsNot Nothing Then
                writer.WriteValue(value.StringValue)
            ElseIf value.ArrayValue IsNot Nothing Then
                WriteIReadOnlyListOfString(writer, value.ArrayValue)
            Else
                writer.WriteNull()
            End If
        End Sub ' WriteFimStopWords

    End Class ' FimRequestWriter
End Namespace
